/*++

Copyright (C) 2019 Autodesk

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.6.0-RC1.

Abstract: This is an autogenerated C++ application that demonstrates the
 usage of the Dynamic C++ bindings of Wibble

Interface version: 0.0.1

*/

#include <iostream>
#include "wibble_dynamic.hpp"


int main()
{
  try
  {
    std::string libpath = (""); // TODO: put the location of the Wibble-library file here.
    auto wrapper = Wibble::CWrapper::loadLibrary(libpath + "/wibble."); // TODO: add correct suffix of the library
    Wibble_uint32 nMajor, nMinor, nMicro;
    wrapper->(nMajor, nMinor, nMicro);
    std::cout << "Wibble.Version = " << nMajor << "." << nMinor << "." << nMicro;
    std::cout << std::endl;
  }
  catch (std::exception &e)
  {
    std::cout << e.what() << std::endl;
    return 1;
  }
  return 0;
}

