/*++

Copyright (C) 2019 Autodesk

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.6.0-RC1.

Abstract: This is an autogenerated C++-Header file in order to allow an easy
 use of Wibble

Interface version: 0.0.1

*/

#ifndef __WIBBLE_DYNAMICHEADER_CPPTYPES
#define __WIBBLE_DYNAMICHEADER_CPPTYPES

#include "wibble_types.hpp"



/*************************************************************************************************************************
 Class definition for Base
**************************************************************************************************************************/

/*************************************************************************************************************************
 Global functions
**************************************************************************************************************************/

/*************************************************************************************************************************
 Function Table Structure
**************************************************************************************************************************/

typedef struct {
  void * m_LibraryHandle;
} sWibbleDynamicWrapperTable;

#endif // __WIBBLE_DYNAMICHEADER_CPPTYPES

