/*++

Copyright (C) 2019 Autodesk

All rights reserved.

This file has been generated by the Automatic Component Toolkit (ACT) version 1.6.0-RC1.

Abstract: This is an autogenerated C++-Header file in order to allow an easy
 use of Wibble

Interface version: 0.0.1

*/

#ifndef __WIBBLE_HEADER_CPP
#define __WIBBLE_HEADER_CPP

#ifdef __WIBBLE_EXPORTS
#ifdef _WIN32
#define WIBBLE_DECLSPEC __declspec (dllexport)
#else // _WIN32
#define WIBBLE_DECLSPEC __attribute__((visibility("default")))
#endif // _WIN32
#else // __WIBBLE_EXPORTS
#define WIBBLE_DECLSPEC
#endif // __WIBBLE_EXPORTS

#include "wibble_types.hpp"


extern "C" {

/*************************************************************************************************************************
 Class definition for Base
**************************************************************************************************************************/

/*************************************************************************************************************************
 Global functions
**************************************************************************************************************************/

}

#endif // __WIBBLE_HEADER_CPP

